version: 2

workflows:
  version: 2
  catling-workflow:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: node:latest
    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install-dependencies
          command: yarn install
      - run:
          name: run-tests
          command: yarn test --coverage
      - run:
          name: build-bundle
          command: yarn build
      - persist_to_workspace:
          root: ./
          paths:
            -  build
      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules